# Generated by Django 4.0.4 on 2022-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('androidid', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('msg', models.CharField(blank=True, max_length=512, null=True)),
                ('package', models.CharField(blank=True, max_length=10, null=True)),
                ('RegDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
