# Generated by Django 4.0.4 on 2022-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetais',
            name='Device',
        ),
        migrations.AddField(
            model_name='device',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdetais',
            name='androidid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
