# Generated by Django 4.0.4 on 2022-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_registrationdetais_androidid1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetais',
            name='androidid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
