# Generated by Django 4.0.4 on 2022-05-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='numOfNotif',
            field=models.IntegerField(default=0),
        ),
    ]
