# Generated by Django 4.0.4 on 2022-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_device_delete_adddata_alter_notification_androidid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='androidid',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
