# Generated by Django 4.0.4 on 2022-05-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_registrationdetais_androidid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
