# Generated by Django 4.0.4 on 2022-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(blank=True, max_length=30, null=True)),
                ('androidid', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('androidid1', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('androidid2', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
