# Generated by Django 4.0.4 on 2022-05-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_device_numofnotif'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='userName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
