# Generated by Django 4.0.4 on 2022-05-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_device_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='userName',
        ),
    ]
