# Generated by Django 4.0.4 on 2022-04-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_registration_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='RegistrationDetais',
        ),
    ]
