# Generated by Django 4.0.4 on 2022-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_device_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetais',
            name='ncount',
        ),
        migrations.RemoveField(
            model_name='registrationdetais',
            name='ntime',
        ),
        migrations.AlterField(
            model_name='registrationdetais',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
