# Generated by Django 4.0.4 on 2022-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_registration_registrationdetais'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetais',
            name='androidid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
