# Generated by Django 4.0.4 on 2022-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_registrationdetais_androidid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetais',
            name='androidid',
        ),
    ]
