# Generated by Django 4.0.4 on 2022-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_registrationdetais_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('androidid', models.CharField(blank=True, max_length=40, null=True)),
                ('package', models.CharField(blank=True, max_length=10, null=True)),
                ('forwardURL', models.URLField()),
            ],
        ),
    ]
