# Generated by Django 4.0.4 on 2022-06-15 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_messageforward'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageforward',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
