# Generated by Django 4.0.4 on 2022-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_registrationdetais_androidid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ntime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetais',
            name='ntime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
