# Generated by Django 4.0.4 on 2022-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_messageforward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageforward',
            name='mtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
