# Generated by Django 4.0.4 on 2022-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_notification_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='RegDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
