# Generated by Django 4.0.4 on 2022-06-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_messageforward_mtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageforward',
            name='date',
        ),
        migrations.RemoveField(
            model_name='messageforward',
            name='mtime',
        ),
    ]
