# Generated by Django 4.0.4 on 2022-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_messageforward_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ForwardService',
            field=models.BooleanField(default=False),
        ),
    ]
