# Generated by Django 4.0.4 on 2022-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_notification_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reciveDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
