# Generated by Django 4.0.4 on 2022-06-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_device_forwardservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('androidid', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('msg', models.CharField(blank=True, max_length=512, null=True)),
                ('forwardURL', models.URLField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
