# Generated by Django 4.0.4 on 2022-04-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_notification_recivedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='RegDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
