# Generated by Django 4.0.4 on 2022-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_forwardhistorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardhistorylog',
            name='package',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
