# Generated by Django 4.0.4 on 2022-06-20 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_forwardhistorylog_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardhistorylog',
            name='fdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 20, 11, 59, 20, 136420)),
        ),
    ]
