# Generated by Django 4.0.4 on 2022-04-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_notification_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetais',
            name='ncount',
            field=models.IntegerField(default=0),
        ),
    ]
