# Generated by Django 4.0.4 on 2022-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_registrationdetais_ncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetais',
            name='androidid1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='registrationdetais',
            name='androidid2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
