# Generated by Django 4.0.4 on 2022-06-20 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_forwardhistorylog_fdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwardhistorylog',
            name='ftime',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 6, 20, 12, 10, 35, 471698)),
        ),
        migrations.AlterField(
            model_name='forwardhistorylog',
            name='fdate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 20, 12, 10, 35, 471698)),
        ),
    ]
