# Generated by Django 4.0.4 on 2022-04-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_device_androidid1_device_androidid2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetais',
            name='androidid1',
        ),
        migrations.RemoveField(
            model_name='registrationdetais',
            name='androidid2',
        ),
    ]
