# Generated by Django 4.0.4 on 2022-04-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_registrationdetais_androidid1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='androidid1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='androidid2',
        ),
    ]
