# Generated by Django 4.0.4 on 2022-04-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_registrationdetais_androidid1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='androidid1',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='androidid2',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
